version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: 172.21.0.3:8084/ganasys-docker:123
    ports:
      - "5050:5000"
    env_file:
      - ./tesis_tesis_asi_rama_carmen/.env      
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - JWT_KEY=${JWT_KEY}
      - POSTGRESQL_HOST=db
      - POSTGRESQL_PORT=5432
      - POSTGRESQL_USER=${POSTGRESQL_USER}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_DB=${POSTGRESQL_DB}
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_DB: ${POSTGRESQL_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
