version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: carmenresquin
      POSTGRES_DB: thesis
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    image: 172.21.0.3:8084/ganasys-tesis_asi_rama_carmen:20241210_0835e0b
    ports:
      - "5050:5050"  # Mapea el puerto externo 5050 al 5000 interno
    environment:
      FLASK_APP: src
      FLASK_ENV: production  # Cambia a producción
      SECRET_KEY: B!1w8*NAt1T^%kvhUI*S^_
      POSTGRESQL_HOST: db
      POSTGRESQL_PORT: 5432
      POSTGRESQL_USER: postgres
      POSTGRESQL_PASSWORD: carmenresquin
      POSTGRESQL_DB: thesis
      JWT_KEY: D5*F?_1?-d$f*1
    depends_on:
      - db

volumes:
  postgres_data:
