version: "3.9"
services:
  web:
    image: 172.21.0.3:8084/ganasys-docker:20241123_533268b
    ports:
      - "5050:5000"   
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
